memory_limit = 512M
max_execution_time = 120

upload_max_filesize = 32M
post_max_size = 32M

date.timezone = UTC

; Development settings. Flip display_errors off and validate_timestamps to 0
; for a production image.
display_errors = On
error_reporting = E_ALL

opcache.enable = 1
opcache.enable_cli = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000